### ISSUE TITLE
 Add linting to the Python project

### ISSUE THREAD

**Issue by chussenot** [YounitedCredit/younited-genaibots#8]
**Description:**
Currently, our project lacks automated linting, which helps ensure code quality and adherence to coding standards. This issue aims to integrate linting tools into our project to improve code consistency and catch potential errors early.

**Tasks:**
1. **Install `flake8` for linting:**
   - Add `flake8` to the development dependencies using `pdm`:
     ```sh
     pdm add --dev flake8
     ```
   - Run `flake8` to lint all Python files:
     ```sh
     pdm run flake8 .
     ```

2. **Install `pylint` for comprehensive linting:**
   - Add `pylint` to the development dependencies using `pdm`:
     ```sh
     pdm add --dev pylint
     ```
   - Run `pylint` to lint all Python files:
     ```sh
     pdm run pylint $(find . -name "*.py") # Must be tuned...
     ```

3. **Install `black` for code formatting:**
   - Add `black` to the development dependencies using `pdm`:
     ```sh
     pdm add --dev black
     ```
   - Run `black` to format all Python files:
     ```sh
     pdm run black .
     ```

4. **Set up pre-commit hooks:**
   - Install `pre-commit` to manage pre-commit hooks:
     ```sh
     pdm add --dev pre-commit
     ```
   - Create a `.pre-commit-config.yaml` file in the root of the project with the following content:
     ```yaml
     repos:
       - repo: https://github.com/pre-commit/pre-commit-hooks
         rev: v4.0.1
         hooks:
           - id: trailing-whitespace
           - id: end-of-file-fixer
           - id: check-yaml

       - repo: https://github.com/psf/black
         rev: 23.3.0
         hooks:
           - id: black

       - repo: https://github.com/pycqa/flake8
         rev: v4.0.1
         hooks:
           - id: flake8

       - repo: https://github.com/pre-commit/mirrors-pylint
         rev: v2.13.4
         hooks:
           - id: pylint
     ```
   - Install the pre-commit hooks:
     ```sh
     pdm run pre-commit install
     ```

**Acceptance Criteria:**
- All Python files in the project should pass `flake8` and `pylint` checks.
- All Python files should be formatted according to `black` standards.
- Pre-commit hooks should be configured and functional, running `black`, `flake8`, and `pylint` before each commit.

**Additional Context:**
Screenshots or logs showing the current issues with linting or formatting can be attached here.
